#configuration file for app
#Application identifier is hellovanessa
#This code runs in go environment, with API version go1
#Every request to a URL whos path matches the regular expression /.* (which is all URLS) should be handled by the Go program.
#The _go_app value is a string recognized by the development web server and is ignored by the production App Engine servers. 

#All Go packages for a given app are built into a single executable, and request dispatch is handled by the Go program itself. 
#This is why we have called http.HandleFunc inside the init function to associate our handler with the web root ("/")

application: stacktracker-1184
version: 1
runtime: go
api_version: go1
automatic_scaling:
  min_idle_instances: 2
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /stylesheets
  static_dir: public/stylesheets

- url: /javascripts
  static_dir: public/javascripts

- url: /images
  static_dir: public/images

- url: /.*
  script: _go_app

inbound_services:
  - warmup

env variables:
  - DB_STRING: 'meredithl:mernessa@tcp([2001:4860:4864:1:aebb:124d:884e:3108]:3306)/mernessa' 
